# Generated by Django 6.0.7 on 2026-10-07 12:36

import django.db.models.deletion
import termos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, unique=True, verbose_name='tipo')),
                ('codigo', models.CharField(max_length=40, verbose_name='código do documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('revisao', models.CharField(default='00', max_length=5, verbose_name='revisão')),
                ('preparado_por', models.CharField(blank=True, max_length=120, verbose_name='preparado por')),
                ('revisado_por', models.CharField(blank=True, max_length=120, verbose_name='revisado por')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name': 'documento de termo',
                'verbose_name_plural': 'documentos de termo',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10, verbose_name='tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=12, verbose_name='status')),
                ('numero_assunto', models.CharField(blank=True, max_length=60, verbose_name='nº do assunto')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('data', models.DateField(verbose_name='data')),
                ('cliente_contato', models.CharField(max_length=200, verbose_name='cliente e pessoa de contato')),
                ('origem', models.CharField(blank=True, max_length=200, verbose_name='origem (projeto / parque específico)')),
                ('transporte', models.CharField(blank=True, max_length=120, verbose_name='transporte')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('assinatura_texas', models.ImageField(blank=True, null=True, upload_to='termos/assinaturas/%Y/%m', verbose_name='assinatura do responsável Texas')),
                ('responsavel_texas', models.CharField(blank=True, max_length=150, verbose_name='responsável Texas')),
                ('assinatura_cliente', models.ImageField(blank=True, null=True, upload_to='termos/assinaturas/%Y/%m', verbose_name='assinatura do cliente')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, verbose_name='nome legível do cliente')),
                ('telefone_cliente', models.CharField(blank=True, max_length=30, verbose_name='telefone do cliente')),
                ('documento_revisao', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(help_text='Revisão do documento usada ao finalizar (cabeçalho do PDF).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='termos.modelotermo')),
            ],
            options={
                'verbose_name': 'termo',
                'verbose_name_plural': 'termos',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=termos.models.foto_termo_path)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='termos.termo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TermoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='equipamento')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('informacao', models.CharField(blank=True, max_length=200, verbose_name='informação')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='termos.termo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
