# Generated by Django 6.0.7 on 2026-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('student_name', models.CharField(max_length=150, verbose_name='nome do aluno')),
                ('course_title', models.CharField(max_length=150, verbose_name='curso')),
                ('instructor_name', models.CharField(max_length=150, verbose_name='instrutor')),
                ('course_date', models.DateField(verbose_name='data do curso')),
                ('duration', models.CharField(max_length=50, verbose_name='duração')),
                ('issue_date', models.DateField(verbose_name='data de emissão')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-issue_date'],
            },
        ),
    ]
