# Generated by Django 6.0.7 on 2026-08-03 13:55

import certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título do curso')),
                ('default_subject_number', models.CharField(blank=True, max_length=9, verbose_name='número do assunto padrão')),
                ('syllabus_items', models.TextField(blank=True, help_text='Um item por linha', verbose_name='conteúdo programático')),
                ('default_duration', models.CharField(blank=True, max_length=50, verbose_name='duração padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modelo de certificado',
                'verbose_name_plural': 'modelos de certificado',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('sigla', models.CharField(max_length=4, unique=True, verbose_name='sigla')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=certificates.models.signature_upload_path, verbose_name='assinatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='assunto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(max_length=200, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='instrutor'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.coursetemplate'),
        ),
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_qr_code', models.BooleanField(default=True, verbose_name='mostrar QR code de verificação')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.professor', verbose_name='coordenador (segunda assinatura)')),
            ],
            options={
                'verbose_name': 'configurações de certificado',
                'verbose_name_plural': 'configurações de certificado',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.professor'),
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='nome do aluno')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('subject_code', models.CharField(max_length=9, verbose_name='assunto')),
                ('course_date', models.DateField(verbose_name='data do curso')),
                ('duration', models.CharField(max_length=50, verbose_name='duração')),
                ('cert_type', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='certificates.coursetemplate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_registrations', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='certificates.professor')),
            ],
            options={
                'verbose_name': 'cadastro de aluno',
                'verbose_name_plural': 'cadastros de alunos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='source_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='certificates.studentregistration'),
        ),
    ]
