# Generated by Django 6.0.7 on 2026-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_coursetemplate_professor_certificate_cert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='word_template',
            field=models.FileField(blank=True, null=True, upload_to='course_templates/word/', verbose_name='modelo em Word'),
        ),
    ]
