# Generated by Django 6.0.7 on 2026-08-04 13:52

import django.db.models.deletion
from django.db import migrations, models


def copy_coordinator(apps, schema_editor):
    CertificateSettings = apps.get_model('certificates', 'CertificateSettings')
    for settings_obj in CertificateSettings.objects.exclude(coordinator__isnull=True):
        settings_obj.coordinator_interno = settings_obj.coordinator
        settings_obj.coordinator_externo = settings_obj.coordinator
        settings_obj.save(update_fields=['coordinator_interno', 'coordinator_externo'])


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_coursetemplate_word_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='coordinator_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.professor', verbose_name='instrutor chefe (certificados externos)'),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='coordinator_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.professor', verbose_name='instrutor chefe (certificados internos)'),
        ),
        migrations.RunPython(copy_coordinator, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='certificatesettings',
            name='coordinator',
        ),
    ]
