# Generated by Django 6.0.7 on 2026-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_split_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatesettings',
            name='coordinator_externo',
        ),
        migrations.RemoveField(
            model_name='certificatesettings',
            name='coordinator_interno',
        ),
        migrations.AddField(
            model_name='professor',
            name='chief_cert_type',
            field=models.CharField(blank=True, choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10, verbose_name='tipo de certificado (instrutor chefe)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='é instrutor chefe'),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_chief', True), models.Q(('chief_cert_type', ''), _negated=True)), fields=('chief_cert_type',), name='one_chief_per_cert_type'),
        ),
    ]
