# Generated by Django 6.0.7 on 2026-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_chief_flag_on_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_height_pt',
            field=models.PositiveIntegerField(default=50, verbose_name='altura padrão da assinatura (pt)'),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_width_pt',
            field=models.PositiveIntegerField(default=120, verbose_name='largura padrão da assinatura (pt)'),
        ),
    ]
