# Generated by Django 6.0.7 on 2026-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_signature_size_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_offset_x_pt',
            field=models.IntegerField(default=0, help_text='Positivo move para a direita, negativo para a esquerda.', verbose_name='deslocamento horizontal da assinatura (pt)'),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_offset_y_pt',
            field=models.IntegerField(default=0, help_text='Positivo move para baixo, negativo para cima (mais perto do nome).', verbose_name='deslocamento vertical da assinatura (pt)'),
        ),
    ]
