# Generated by Django 6.0.7 on 2026-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_signature_position_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_dark_threshold',
            field=models.PositiveIntegerField(default=60, help_text='Pixels mais escuros que isso ficam totalmente opacos (tom mais forte). Aumente para deixar o traço mais escuro/nítido.', verbose_name='limite de preto (0-255)'),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_invert_colors',
            field=models.BooleanField(default=False, help_text='Ative se as assinaturas enviadas forem traço claro sobre fundo escuro, em vez de tinta escura sobre papel claro.', verbose_name='assinatura com fundo escuro (inverter)'),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='signature_light_threshold',
            field=models.PositiveIntegerField(default=225, help_text='Pixels mais claros que isso viram transparentes. Diminua se a assinatura ficar com fundo esbranquiçado; aumente se partes do traço estiverem sumindo.', verbose_name='limite de branco (0-255)'),
        ),
    ]
