# Generated by Django 6.0.7 on 2026-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_remove_certificatesettings_signature_dark_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Professores arquivados não aparecem para seleção em novos certificados, mas o histórico é mantido.', verbose_name='ativo'),
        ),
    ]
