# Generated by Django 6.0.7 on 2026-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_professor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='external_link',
            field=models.CharField(blank=True, help_text='Se preenchido, "Ver" no Histórico abre este link (ex: SharePoint) em vez do PDF gerado pelo sistema.', max_length=500, verbose_name='link externo do certificado'),
        ),
    ]
