# Generated by Django 6.0.7 on 2026-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_certificate_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='client_name',
            field=models.CharField(blank=True, help_text='Ex: nome da empresa ou unidade onde o curso foi dado.', max_length=150, verbose_name='cliente / local do curso'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='client_name',
            field=models.CharField(blank=True, help_text='Ex: nome da empresa ou unidade onde o curso foi dado.', max_length=150, verbose_name='cliente / local do curso'),
        ),
    ]
