# Generated by Django 6.0.7 on 2026-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('vistoriador', 'Vistoriador (mobilização)')], default='professor', max_length=20),
        ),
    ]
