# Generated by Django 6.0.7 on 2026-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('vistoriador', 'Vistoriador (mobilização)'), ('tecnico', 'Técnico de campo (checklists)')], default='professor', max_length=20),
        ),
    ]
