# Generated by Django 6.0.7 on 2026-10-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_papeis_tecnico_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonte',
            field=models.CharField(choices=[('manrope', 'Manrope (padrão)'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('open_sans', 'Open Sans'), ('atkinson', 'Atkinson Hyperlegible (leitura fácil)'), ('lexend', 'Lexend')], default='manrope', max_length=20, verbose_name='fonte'),
        ),
        migrations.AddField(
            model_name='user',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('auto', 'Automático (segue o celular ou computador)')], default='claro', max_length=10, verbose_name='tema'),
        ),
    ]
