# Generated by Django 6.0.7 on 2026-09-30 11:54

import django.db.models.deletion
import veiculos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='nº da CNH')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='validade da CNH')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'motorista',
                'verbose_name_plural': 'motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('saida', 'Saída'), ('chegada', 'Chegada'), ('rotina', 'Rotina')], default='rotina', max_length=10, verbose_name='tipo')),
                ('km', models.PositiveIntegerField(verbose_name='km no painel')),
                ('combustivel', models.CharField(blank=True, choices=[('reserva', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=10, verbose_name='combustível')),
                ('destino', models.CharField(blank=True, max_length=200, verbose_name='destino / motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('tem_problema', models.BooleanField(default=False, verbose_name='tem problema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('email_enviado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes', to='veiculos.motorista')),
            ],
            options={
                'verbose_name': 'inspeção',
                'verbose_name_plural': 'inspeções',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspecaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=veiculos.models.inspection_photo_path)),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='veiculos.inspecao')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='placa')),
                ('marca', models.CharField(max_length=60, verbose_name='marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='modelo')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='cor')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='km atual')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=veiculos.models.vehicle_photo_path, verbose_name='foto')),
                ('licenciamento_validade', models.DateField(blank=True, null=True, verbose_name='vencimento do licenciamento')),
                ('seguro_validade', models.DateField(blank=True, null=True, verbose_name='vencimento do seguro')),
                ('revisao_data', models.DateField(blank=True, null=True, verbose_name='próxima revisão (data)')),
                ('revisao_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='próxima revisão (km)')),
                ('checklist_frequencia_dias', models.PositiveIntegerField(default=7, help_text='Se o veículo ficar mais que isso sem inspeção, o motorista e os supervisores recebem um lembrete.', verbose_name='checklist a cada (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='veiculos.motorista', verbose_name='motorista responsável')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=200, verbose_name='destino / motivo')),
                ('saida_em', models.DateTimeField(verbose_name='saída')),
                ('km_saida', models.PositiveIntegerField(verbose_name='km de saída')),
                ('chegada_em', models.DateTimeField(blank=True, null=True, verbose_name='chegada')),
                ('km_chegada', models.PositiveIntegerField(blank=True, null=True, verbose_name='km de chegada')),
                ('inspecao_chegada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_chegada', to='veiculos.inspecao')),
                ('inspecao_saida', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_saida', to='veiculos.inspecao')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='veiculos.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'uso',
                'verbose_name_plural': 'usos da frota',
                'ordering': ['-saida_em'],
            },
        ),
        migrations.AddField(
            model_name='inspecao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='veiculos.veiculo'),
        ),
        migrations.CreateModel(
            name='InspecaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('nok', 'Não OK'), ('na', 'N/A')], default='ok', max_length=3)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='veiculos.inspecao')),
            ],
            options={
                'unique_together': {('inspecao', 'item')},
            },
        ),
    ]
