# Generated by Django 6.0.7 on 2026-10-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecaofoto',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='inspecao',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/assinaturas/%Y/%m', verbose_name='assinatura do motorista'),
        ),
        migrations.AddField(
            model_name='inspecaofoto',
            name='posicao',
            field=models.CharField(blank=True, help_text='Chave de FOTO_POSICOES; vazio para fotos extras.', max_length=20),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Troca de óleo, Pneus, Correia dentada, Filtro de ar.', max_length=80, verbose_name='nome')),
                ('proximo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='próxima no km')),
                ('proxima_data', models.DateField(blank=True, null=True, verbose_name='próxima na data')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='repetir a cada (km)')),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='repetir a cada (meses)')),
                ('aviso_km', models.PositiveIntegerField(default=1000, verbose_name='avisar quando faltarem (km)')),
                ('aviso_dias', models.PositiveIntegerField(default=15, verbose_name='avisar quando faltarem (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'manutenção',
                'verbose_name_plural': 'manutenções',
                'ordering': ['nome'],
            },
        ),
    ]
