# Generated by Django 6.0.7 on 2026-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_inspecaofoto_options_inspecao_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='combustivel_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='combustível (%)'),
        ),
        migrations.AddField(
            model_name='inspecaofoto',
            name='percentual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usado nos pneus: 0 a 100%.', null=True, verbose_name='estado (%)'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('reserva', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=10, verbose_name='combustível (antigo)'),
        ),
    ]
