# Generated by Django 6.0.7 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_inspecao_combustivel_pct_inspecaofoto_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='com_carga',
            field=models.BooleanField(blank=True, help_text='Só para caminhonetes; vazio em carro de passeio.', null=True, verbose_name='leva carga'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('caminhonete', 'Caminhonete'), ('carro', 'Carro de passeio')], default='carro', max_length=12, verbose_name='tipo de veículo'),
        ),
    ]
