# Generated by Django 6.0.7 on 2026-10-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_inspecao_com_carga_veiculo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Quando o vistoriador faz a vistoria, ele mesmo é o motorista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista', to=settings.AUTH_USER_MODEL, verbose_name='login do vistoriador'),
        ),
    ]
