# Generated by Django 6.0.7 on 2026-10-07 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_motorista_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Quando essa pessoa faz a vistoria, ela mesma é o motorista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista', to=settings.AUTH_USER_MODEL, verbose_name='login do técnico'),
        ),
    ]
