# Generated by Django 6.0.7 on 2026-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('veiculos', '0006_alter_motorista_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name'], 'verbose_name': 'destinatário', 'verbose_name_plural': 'destinatários'},
        ),
        migrations.AddField(
            model_name='supervisor',
            name='recebe_checklists',
            field=models.BooleanField(default=True, verbose_name='checklists de equipamentos'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='recebe_termos',
            field=models.BooleanField(default=True, verbose_name='termos de entrada e saída'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='recebe_veiculos',
            field=models.BooleanField(default=True, verbose_name='vistorias de veículos e avisos da frota'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='tipos_ativo',
            field=models.ManyToManyField(blank=True, help_text='Deixe tudo desmarcado para receber de todos os tipos.', related_name='destinatarios', to='checklists.tipoativo', verbose_name='só destes tipos de equipamento'),
        ),
    ]
