"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env (nunca commitado - veja .env.example)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-_x+=jfs(@((6e60*cds%ct*ofqe_zudctmikig2#k%6$gr_1r2',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Microsoft Entra ID / Graph API (usado para acessar o SharePoint via Sites.Selected)
MS_GRAPH = {
    'TENANT_ID': os.environ.get('MS_TENANT_ID', ''),
    'CLIENT_ID': os.environ.get('MS_CLIENT_ID', ''),
    'CLIENT_SECRET': os.environ.get('MS_CLIENT_SECRET', ''),
    'SHAREPOINT_HOSTNAME': os.environ.get('MS_SHAREPOINT_HOSTNAME', ''),
    'SHAREPOINT_SITE_PATH': os.environ.get('MS_SHAREPOINT_SITE_PATH', ''),
    'SHAREPOINT_SITE_ID': os.environ.get('MS_SHAREPOINT_SITE_ID', ''),
    'EXCEL_ITEM_PATH': os.environ.get('MS_EXCEL_ITEM_PATH', ''),
    'CERTIFICATES_FOLDER_PATH': os.environ.get('MS_CERTIFICATES_FOLDER_PATH', ''),
    'EXCEL_SHARE_URL': os.environ.get('MS_EXCEL_SHARE_URL', ''),
    'CERTIFICATES_FOLDER_SHARE_URL': os.environ.get('MS_CERTIFICATES_FOLDER_SHARE_URL', ''),
    'EXCEL_CODE_COLUMN': os.environ.get('MS_EXCEL_CODE_COLUMN', 'Código'),
    'EXCEL_LINK_COLUMN': os.environ.get('MS_EXCEL_LINK_COLUMN', 'Link'),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'certificates',
    'dashboard',
]

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:auth'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:auth'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOFFICE_PATH = r'C:\Program Files\LibreOffice\program\soffice.exe'
