# Generated by Django 6.0.7 on 2026-10-05 14:00

import checklists.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Como o equipamento é conhecido, ex.: Bancada RAD 02.', max_length=150, verbose_name='nome')),
                ('identificacao', models.CharField(max_length=80, verbose_name='identificação / nº de série')),
                ('patrimonio', models.CharField(blank=True, max_length=40, verbose_name='patrimônio')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='modelo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=12, verbose_name='status')),
                ('medidor_atual', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='leitura atual do medidor')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ativo',
                'verbose_name_plural': 'ativos',
                'ordering': ['tipo__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='item')),
                ('tipo_resposta', models.CharField(choices=[('ok_nok', 'OK / NOK / N/A'), ('conformidade', 'Conforme / Não conforme / Parcialmente / N/A'), ('sim_nao', 'Sim / Não'), ('porcentagem', 'Porcentagem (0 a 100%)'), ('numero', 'Número'), ('texto', 'Texto livre')], default='ok_nok', max_length=16, verbose_name='tipo de resposta')),
                ('exige_foto', models.BooleanField(default=False, verbose_name='exige foto')),
                ('observacao', models.CharField(choices=[('se_negativo', 'Só quando a resposta for negativa'), ('sempre', 'Sempre'), ('nunca', 'Nunca')], default='se_negativo', max_length=12, verbose_name='pede observação')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: TCB-OTB-80', max_length=40, unique=True, verbose_name='código do documento')),
                ('titulo', models.CharField(help_text='Ex.: Checklist de pré-uso – Bancada de calibração', max_length=200, verbose_name='título')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponível para execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modelo de checklist',
                'verbose_name_plural': 'modelos de checklist',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Família de equipamentos, ex.: Gerador, Chave elétrica de torque, Transpaleteira.', max_length=120, unique=True, verbose_name='nome')),
                ('medidor', models.CharField(choices=[('nenhum', 'Sem medidor'), ('horimetro', 'Horímetro (horas)'), ('km', 'Quilometragem (km)')], default='nenhum', help_text='Leitura pedida em toda execução (ex.: horímetro do gerador).', max_length=12, verbose_name='medidor')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tipo de ativo',
                'verbose_name_plural': 'tipos de ativo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_nome', models.CharField(max_length=150, verbose_name='técnico')),
                ('medidor_valor', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='leitura do medidor')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='checklists/assinaturas/%Y/%m', verbose_name='assinatura do técnico')),
                ('tem_problema', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='checklists.ativo')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_checklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'execução de checklist',
                'verbose_name_plural': 'execuções de checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=checklists.models.foto_execucao_path)),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklists.execucao')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checklists.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='checklists.execucao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='checklists.item')),
            ],
            options={
                'ordering': ['item__secao__ordem', 'item__secao_id', 'item__ordem', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0, verbose_name='revisão')),
                ('preparado_por', models.CharField(blank=True, max_length=120, verbose_name='preparado por')),
                ('revisado_por', models.CharField(blank=True, max_length=120, verbose_name='revisado por')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('vigente', models.BooleanField(default=True, verbose_name='vigente')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='o que mudou')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='checklists.modelo')),
            ],
            options={
                'verbose_name': 'revisão',
                'verbose_name_plural': 'revisões',
                'ordering': ['modelo__codigo', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='execucao',
            name='revisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='checklists.revisao'),
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='checklists.revisao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklists.secao'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='tipos_ativo',
            field=models.ManyToManyField(blank=True, related_name='modelos', to='checklists.tipoativo', verbose_name='aplica-se a'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='checklists.tipoativo', verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='revisao',
            constraint=models.UniqueConstraint(fields=('modelo', 'numero'), name='revisao_unica_por_modelo'),
        ),
    ]
