# Generated by Django 6.0.7 on 2026-10-08 12:59

from django.db import migrations, models


def preencher(apps, schema_editor):
    from checklists.models import finalidade_do_titulo

    Modelo = apps.get_model('checklists', 'Modelo')
    for m in Modelo.objects.all():
        m.finalidade = finalidade_do_titulo(m.titulo)
        m.save(update_fields=['finalidade'])


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='finalidade',
            field=models.CharField(choices=[('pre_uso', 'Pré-uso'), ('inspecao', 'Inspeção'), ('manutencao', 'Manutenção'), ('geral', 'Geral')], default='geral', help_text='Primeiro passo do técnico ao executar: pré-uso, inspeção, manutenção ou geral.', max_length=12, verbose_name='finalidade'),
        ),
        migrations.RunPython(preencher, migrations.RunPython.noop),
    ]
