# Generated by Django 6.0.7 on 2026-10-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_modelo_finalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando o técnico cadastra o equipamento na hora do checklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='identificacao',
            field=models.CharField(blank=True, max_length=80, verbose_name='identificação / nº de série'),
        ),
    ]
